#include <vector>
#include <list>
#include <map>
#include <set>
#include <queue>
#include <deque>
#include <stack>
#include <bitset>
#include <algorithm>
#include <functional>
#include <numeric>
#include <utility>
#include <string>
#include <sstream>
#include <iostream>
#include <iomanip>
#include <cstdio>
#include <cmath>
#include <cstdlib>
#include <ctime>
using namespace std;

#define REP(i,a,b) for(int i=a; i < b; i++)
#define REPE(i, a, b) for(int i=a; i <=b; i++)
int INF = numeric_limits<int>::max();
int nINF = numeric_limits<int>::min();
typedef long long ll;
 
class CubeColoring {
public:
	long long theCount(vector <string>);
};

long long CubeColoring::theCount(vector <string> colors) {
	
    ll res = 0ll;
    int R = colors.size();
    int C = colors[0].size();
    
    bool isGood[R][C];
    for(int i=0; i < R; i++)
        for(int j=0; j < C; j++)
            isGood[i][j] = (colors[i][j] == 'Y');
    
    for(int c0 = 0; c0 < C; c0++)
        for(int c2 = 0; c2 < C; c2++)
            for(int c5 = 0; c5 < C; c5++)
                for(int c7 = 0; c7 < C; c7++)
                    if(isGood[0][c0] && isGood[2][c2] && isGood[5][c5] && isGood[7][c7])
                    {
                        int w1,w3,w4,w6;
                        w1 = w3 = w4 = w6 = 0;
                        for(int c=0; c < C; c++)
                        {
                            if(isGood[1][c] && c != c0 && c != c2 && c != c5) w1++;
                            if(isGood[3][c] && c != c0 && c != c2 && c != c7) w3++;
                            if(isGood[4][c] && c != c0 && c != c5 && c != c7) w4++;
                            if(isGood[6][c] && c != c2 && c != c5 && c != c7) w6++;
                        }
                        res += w1 * w3 * w4 * w6;
                    }
    
    return res;
}

// BEGIN KAWIGIEDIT TESTING
// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
bool KawigiEdit_RunTest(int testNum, vector <string> p0, bool hasAnswer, long long p1) {
	cout << "Test " << testNum << ": [" << "{";
	for (int i = 0; int(p0.size()) > i; ++i) {
		if (i > 0) {
			cout << ",";
		}
		cout << "\"" << p0[i] << "\"";
	}
	cout << "}";
	cout << "]" << endl;
	CubeColoring *obj;
	long long answer;
	obj = new CubeColoring();
	clock_t startTime = clock();
	answer = obj->theCount(p0);
	clock_t endTime = clock();
	delete obj;
	bool res;
	res = true;
	cout << "Time: " << double(endTime - startTime) / CLOCKS_PER_SEC << " seconds" << endl;
	if (hasAnswer) {
		cout << "Desired answer:" << endl;
		cout << "\t" << p1 << endl;
	}
	cout << "Your answer:" << endl;
	cout << "\t" << answer << endl;
	if (hasAnswer) {
		res = answer == p1;
	}
	if (!res) {
		cout << "DOESN'T MATCH!!!!" << endl;
	} else if (double(endTime - startTime) / CLOCKS_PER_SEC >= 2) {
		cout << "FAIL the timeout" << endl;
		res = false;
	} else if (hasAnswer) {
		cout << "Match :-)" << endl;
	} else {
		cout << "OK, but is it right?" << endl;
	}
	cout << "" << endl;
	return res;
}
int main() {
	bool all_right;
	all_right = true;
	
	vector <string> p0;
	long long p1;
	
	{
	// ----- test 0 -----
	string t0[] = {"Y","Y","Y","Y","Y","Y","Y","Y"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 0ll;
	all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 1 -----
	string t0[] = {"YNNNNNNN","NYNNNNNN","NNYNNNNN","NNNYNNNN","NNNNYNNN","NNNNNYNN","NNNNNNYN","NNNNNNNY"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 1ll;
	all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 2 -----
	string t0[] = {"YNNYN","YYYYY","NYYNY","YNYYN","YNNYY","YNNYY","NNNYY","NYYYY"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 250ll;
	all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 3 -----
	string t0[] = {"YNNYN","YYYYY","NNNNN","YNYYN","YNNYY","YNNYY","NNNYY","NYYYY"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 0ll;
	all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
	// ------------------
	}
	
	{
	// ----- test 4 -----
	string t0[] = {"YNNYNYYYYYNN","NNNYNYYNYNNY","YYNNYYNNNYYN","YYYYYNNYYYNN","NNNYYYNNYNYN","YYYNYYYYNYNN","NNNNNNYYNYYN","NNYNYYNNYNYY"};
			p0.assign(t0, t0 + sizeof(t0) / sizeof(t0[0]));
	p1 = 611480ll;
	all_right = KawigiEdit_RunTest(4, p0, true, p1) && all_right;
	// ------------------
	}
	
	if (all_right) {
		cout << "You're a stud (at least on the example cases)!" << endl;
	} else {
		cout << "Some of the test cases had errors." << endl;
	}
	return 0;
}
// END KAWIGIEDIT TESTING


//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
